-- A third provenance: content generated by the conjugation engine.
--
-- Migration 003 recorded two ways a drill can reach the `content` table —
-- `authored` (written by hand) and `gauntlet` (generated by a model and passed
-- through SPEC §5's panel of verifiers). It said so precisely because the
-- invariant "never show the user content that has not been verified" is only
-- honest if the table records how each row was verified.
--
-- `domain/conjugation.ts` is a third way, and it needs its own name rather
-- than being filed under either of the existing two.
--
-- It is not `authored`: nobody wrote «habríamos ejecutado» by hand, and
-- claiming they did would misattribute the work and hide the fact that the row
-- can be regenerated at will.
--
-- It is not `gauntlet`: the panel never saw it, and giving it a gauntlet score
-- would be inventing a verification that did not happen. That is the exact
-- dishonesty migration 003 was written to prevent.
--
-- What it is: output of a deterministic engine whose correctness is established
-- by an exhaustive test suite rather than by a panel. That is a stronger
-- guarantee for this kind of content, not a weaker one — a conjugation has one
-- right answer and no judgement call for a verifier to make — but it is a
-- *different* guarantee, and the column should say which one a row carries.
--
-- SQLite cannot alter a CHECK constraint in place, so the table is rebuilt.
-- See the runner's REBUILD_MARKER handling for why this needs the marker.

-- fluencia:rebuild-tables

CREATE TABLE content_new (
  id            INTEGER PRIMARY KEY AUTOINCREMENT,
  topic_id      TEXT NOT NULL REFERENCES topic(id),
  kind          TEXT NOT NULL CHECK (kind IN (
                  'explanation','drill_conjugation','drill_cloze','drill_transform',
                  'drill_translate','drill_error_spot','roleplay','upgrade_pair')),
  difficulty    INTEGER NOT NULL CHECK (difficulty BETWEEN 1 AND 5),
  payload       TEXT NOT NULL,
  targets_error TEXT REFERENCES error(code),
  gauntlet_score REAL NOT NULL,
  gauntlet_log  TEXT NOT NULL,
  verified_at   TEXT NOT NULL,
  retired       INTEGER DEFAULT 0,
  provenance    TEXT NOT NULL DEFAULT 'gauntlet'
                CHECK (provenance IN ('authored', 'gauntlet', 'engine')),
  seed_key      TEXT
);

INSERT INTO content_new
  (id, topic_id, kind, difficulty, payload, targets_error, gauntlet_score,
   gauntlet_log, verified_at, retired, provenance, seed_key)
SELECT
   id, topic_id, kind, difficulty, payload, targets_error, gauntlet_score,
   gauntlet_log, verified_at, retired, provenance, seed_key
  FROM content;

DROP TABLE content;
ALTER TABLE content_new RENAME TO content;

CREATE INDEX idx_content_topic ON content(topic_id, retired);
CREATE UNIQUE INDEX idx_content_seed_key ON content(seed_key);
