import type { SeedVocab } from './types';

/**
 * B2 vocabulary, chosen for the job rather than for a frequency list.
 *
 * The selection rule: a word earns a place if it appears in a Lima
 * infrastructure consultant's week and its absence would force a paraphrase.
 * That excludes plenty of common B2 vocabulary and includes some words a
 * general course would call C1 — «adenda», «valorización», «penalidad» are not
 * advanced, they are Tuesday.
 *
 * Categories mirror §2's enum. The most valuable are `connector` (what an
 * examiner listens for) and `false_friend` (what costs you money).
 *
 * Register: neutral Latin American throughout, Peruvian contracting usage where
 * the two differ. Enforced by the register suite in seed.test.ts.
 */
export const VOCAB: SeedVocab[] = [
  /* ---------------- connectors: the B2 exam's own checklist ---------------- */
  { term: 'sin embargo', gloss: 'however', category: 'connector', level: 'B1',
    example: 'El diseño está aprobado; sin embargo, el presupuesto sigue en revisión.' },
  { term: 'no obstante', gloss: 'nevertheless (formal)', category: 'connector', level: 'B2',
    example: 'No obstante lo acordado en el acta, el proveedor cambió la especificación.' },
  { term: 'por lo tanto', gloss: 'therefore', category: 'connector', level: 'B1',
    example: 'El proveedor no confirmó la fecha; por lo tanto, reprogramamos el vaciado.' },
  { term: 'en consecuencia', gloss: 'consequently (formal)', category: 'connector', level: 'B2',
    example: 'Se detectó una interferencia en la losa; en consecuencia, se detuvo el encofrado.' },
  { term: 'siempre y cuando', gloss: 'provided that', category: 'connector', level: 'B2',
    example: 'Empezamos el lunes siempre y cuando el cliente confirme el presupuesto.' },
  { term: 'a raíz de', gloss: 'as a result of, stemming from', category: 'connector', level: 'B2',
    example: 'A raíz de la observación de la supervisión, rehicimos el cálculo estructural.' },
  { term: 'en la medida en que', gloss: 'insofar as, to the extent that', category: 'connector', level: 'B2',
    example: 'Podemos comprimir el plazo en la medida en que se libere el frente de trabajo.' },
  { term: 'dado que', gloss: 'given that', category: 'connector', level: 'B2',
    example: 'Dado que el expediente está incompleto, la valorización queda observada.' },
  { term: 'a su vez', gloss: 'in turn', category: 'connector', level: 'B2',
    example: 'El retraso afecta al montaje, y este a su vez a las pruebas de operación.' },
  { term: 'de ahí que', gloss: 'hence (takes the subjunctive)', category: 'connector', level: 'B2',
    example: 'El terreno resultó más blando de lo previsto; de ahí que reforcemos la cimentación.' },
  { term: 'ahora bien', gloss: 'that said', category: 'connector', level: 'B2',
    example: 'El avance físico va bien. Ahora bien, la curva de costos preocupa.' },
  { term: 'en cuanto a', gloss: 'as regards', category: 'connector', level: 'B1',
    example: 'En cuanto a la seguridad, cerramos las tres observaciones de la semana pasada.' },

  /* ---------------- the contract and the money ---------------- */
  { term: 'la valorización', gloss: 'progress valuation / payment application', category: 'work_noun', level: 'B2',
    example: 'Presentamos la valorización del mes con el metrado verificado en campo.' },
  { term: 'la adenda', gloss: 'contract addendum', category: 'work_noun', level: 'B2',
    example: 'La ampliación de plazo se formalizó mediante una adenda al contrato.' },
  { term: 'el adicional', gloss: 'variation, change order', category: 'work_noun', level: 'B2',
    example: 'El adicional por mayores metrados todavía no cuenta con aprobación.' },
  { term: 'la penalidad', gloss: 'liquidated damages, contractual penalty', category: 'work_noun', level: 'B2',
    example: 'El contrato prevé una penalidad diaria por cada día de atraso en la entrega.' },
  { term: 'el expediente técnico', gloss: 'technical dossier, design package', category: 'work_noun', level: 'B2',
    example: 'El expediente técnico se entregó con los planos y la memoria de cálculo.' },
  { term: 'el acta de conformidad', gloss: 'sign-off certificate', category: 'work_noun', level: 'B2',
    example: 'No podemos facturar sin el acta de conformidad firmada por la supervisión.' },
  { term: 'la partida', gloss: 'line item, work package', category: 'work_noun', level: 'B2',
    example: 'La partida de instalaciones eléctricas quedó fuera del alcance original.' },
  { term: 'el metrado', gloss: 'quantity take-off', category: 'work_noun', level: 'B2',
    example: 'Revisamos el metrado antes de facturar para evitar una observación.' },
  { term: 'el alcance', gloss: 'scope', category: 'work_noun', level: 'B1',
    example: 'Cualquier cambio de alcance debe quedar registrado por escrito.' },
  { term: 'la observación', gloss: 'formal objection, snag', category: 'work_noun', level: 'B2',
    example: 'La supervisión levantó dos observaciones sobre el acabado de la fachada.' },
  { term: 'el plazo', gloss: 'deadline, term', category: 'work_noun', level: 'B1',
    example: 'El plazo contractual vence a fin de mes y el frente sigue abierto.' },
  { term: 'la licitación', gloss: 'tender, bidding process', category: 'work_noun', level: 'B2',
    example: 'La licitación se declaró desierta porque ningún postor cumplió los requisitos.' },
  { term: 'el postor', gloss: 'bidder', category: 'work_noun', level: 'B2',
    example: 'Solo dos postores presentaron propuesta técnica y económica.' },
  { term: 'la contingencia', gloss: 'contingency (budget or risk)', category: 'work_noun', level: 'B2',
    example: 'Usamos la contingencia para cubrir el sobrecosto del acero.' },
  { term: 'el sobrecosto', gloss: 'cost overrun', category: 'work_noun', level: 'B2',
    example: 'El sobrecosto se explica por la variación del precio del concreto.' },

  /* ---------------- the site ---------------- */
  { term: 'el vaciado', gloss: 'concrete pour', category: 'work_noun', level: 'B1',
    example: 'El vaciado de la losa se programó para el jueves a primera hora.' },
  { term: 'el encofrado', gloss: 'formwork', category: 'work_noun', level: 'B1',
    example: 'La cuadrilla de encofrado necesita dos días más en el segundo nivel.' },
  { term: 'la cimentación', gloss: 'foundations', category: 'work_noun', level: 'B1',
    example: 'Reforzamos la cimentación después del estudio de suelos.' },
  { term: 'la cuadrilla', gloss: 'work crew', category: 'work_noun', level: 'B1',
    example: 'La cuadrilla quedó parada porque no llegó el concreto.' },
  { term: 'el capataz', gloss: 'foreman', category: 'work_noun', level: 'B1',
    example: 'El capataz reportó una interferencia entre la tubería y la viga.' },
  { term: 'la movilización', gloss: 'mobilisation to site', category: 'work_noun', level: 'B2',
    example: 'La movilización de equipos es una partida facturable del contrato.' },
  { term: 'el frente de trabajo', gloss: 'work front, available work area', category: 'work_noun', level: 'B2',
    example: 'No podemos avanzar hasta que el cliente libere el frente de trabajo.' },
  { term: 'la interferencia', gloss: 'clash (between services)', category: 'work_noun', level: 'B2',
    example: 'Detectamos una interferencia entre el ducto y la estructura metálica.' },

  /* ---------------- verbs that carry the week ---------------- */
  { term: 'subsanar', gloss: 'to remedy, to put right (a defect or objection)', category: 'verb_pattern', level: 'B2',
    example: 'Tenemos cinco días hábiles para subsanar las observaciones.' },
  { term: 'incumplir', gloss: 'to breach, to fail to meet', category: 'verb_pattern', level: 'B2',
    example: 'El proveedor incumplió el plazo de entrega por tercera vez.' },
  { term: 'reprogramar', gloss: 'to reschedule', category: 'verb_pattern', level: 'B1',
    example: 'Reprogramamos la reunión de coordinación para el viernes.' },
  { term: 'sustentar', gloss: 'to substantiate, to back up with evidence', category: 'verb_pattern', level: 'B2',
    example: 'Hay que sustentar el adicional con el metrado y las fotos de campo.' },
  { term: 'agilizar', gloss: 'to speed up, to expedite', category: 'verb_pattern', level: 'B2',
    example: 'Pedimos a la supervisión agilizar la revisión del expediente.' },
  { term: 'prever', gloss: 'to foresee, to make provision for', category: 'verb_pattern', level: 'B2',
    example: 'El cronograma no previó la temporada de lluvias.' },
  { term: 'aprobar', gloss: 'to approve', category: 'verb_pattern', level: 'A2',
    example: 'El supervisor aprobó el cambio de especificación el martes.' },
  { term: 'levantar una observación', gloss: 'to raise — or to clear — a formal objection', category: 'set_phrase', level: 'B2',
    example: 'Levantamos la observación con el ensayo de resistencia del concreto.' },
  { term: 'dar por cerrado', gloss: 'to consider closed', category: 'set_phrase', level: 'B2',
    example: 'Damos por cerrado el punto una vez que llegue el acta firmada.' },
  { term: 'quedar pendiente', gloss: 'to remain outstanding', category: 'set_phrase', level: 'B1',
    example: 'Queda pendiente la confirmación del proveedor de encofrados.' },
  { term: 'estar a cargo de', gloss: 'to be in charge of', category: 'set_phrase', level: 'B1',
    example: 'El ingeniero residente está a cargo de la coordinación con la municipalidad.' },
  { term: 'hacer seguimiento', gloss: 'to follow up on', category: 'set_phrase', level: 'B1',
    example: 'Voy a hacer seguimiento a la consulta que enviamos hace dos semanas.' },

  /* ---------------- delexical verbs: the B2 naturalness marker ---------------- */
  { term: 'tomar una decisión', gloss: 'to make a decision (never «hacer»)', category: 'collocation', level: 'B1',
    example: 'El comité tomó la decisión de postergar el inicio de obra.' },
  { term: 'dar seguimiento', gloss: 'to monitor, to track', category: 'collocation', level: 'B2',
    example: 'Damos seguimiento semanal al avance físico y financiero.' },
  { term: 'llevar a cabo', gloss: 'to carry out', category: 'collocation', level: 'B2',
    example: 'Llevamos a cabo la prueba de estanqueidad el mismo día del vaciado.' },
  { term: 'poner en marcha', gloss: 'to set in motion, to commission', category: 'collocation', level: 'B2',
    example: 'Pusimos en marcha el sistema contra incendios tras las pruebas.' },
  { term: 'plantear una propuesta', gloss: 'to put forward a proposal', category: 'collocation', level: 'B2',
    example: 'Planteamos una propuesta alternativa para reducir el sobrecosto.' },
  { term: 'asumir el costo', gloss: 'to absorb the cost', category: 'collocation', level: 'B2',
    example: 'El contratista asumió el costo del reproceso por su propio error.' },
  { term: 'ceñirse al presupuesto', gloss: 'to stick to the budget', category: 'collocation', level: 'B2',
    example: 'Nos ceñimos al presupuesto aprobado pese a la variación de precios.' },

  /* ---------------- false friends: the ones that cost money ---------------- */
  { term: 'actualmente', gloss: 'currently — NOT "actually"', category: 'false_friend', level: 'B1',
    example: 'Actualmente estamos en la etapa de acabados, no en estructura.' },
  { term: 'eventualmente', gloss: 'possibly, if the case arises — NOT "eventually"', category: 'false_friend', level: 'B2',
    example: 'Eventualmente podríamos necesitar una segunda grúa, según el avance.' },
  { term: 'realizar', gloss: 'to carry out — NOT "to realise" (that is «darse cuenta»)', category: 'false_friend', level: 'B1',
    example: 'Realizamos la inspección conjunta el miércoles por la mañana.' },
  { term: 'asistir a', gloss: 'to attend — NOT "to assist"', category: 'false_friend', level: 'B1',
    example: 'Asistí a la reunión de coordinación en representación del consorcio.' },
  { term: 'la carpeta', gloss: 'folder — NOT "carpet"', category: 'false_friend', level: 'A2',
    example: 'Los planos actualizados están en la carpeta compartida del proyecto.' },
  { term: 'sensible', gloss: 'sensitive — NOT "sensible" (that is «sensato»)', category: 'false_friend', level: 'B2',
    example: 'El cronograma es sensible a cualquier retraso en la procura.' },
  { term: 'la firma', gloss: 'signature, or a firm — NOT "firm" as an adjective', category: 'false_friend', level: 'B1',
    example: 'Falta la firma del residente en el acta de conformidad.' },
  { term: 'discutir', gloss: 'to argue as often as to discuss — «conversar» is the safer verb', category: 'false_friend', level: 'B2',
    example: 'No queremos discutir con el cliente; queremos conversar el punto en la reunión.' },
  { term: 'comprometerse', gloss: 'to commit oneself — NOT "to compromise"', category: 'false_friend', level: 'B2',
    example: 'El proveedor se comprometió a entregar el material antes del vaciado.' },
  { term: 'la agenda', gloss: 'diary as well as meeting agenda', category: 'false_friend', level: 'B1',
    example: 'Envío la agenda de la reunión con los cuatro puntos a tratar.' },

  /* ---------------- hedging: how to disagree and keep the contract ---------------- */
  { term: 'en principio', gloss: 'in principle, as things stand', category: 'set_phrase', level: 'B2',
    example: 'En principio mantenemos la fecha, aunque depende de la procura.' },
  { term: 'habría que', gloss: 'one would have to (impersonal, softened)', category: 'set_phrase', level: 'B2',
    example: 'Habría que revisar el metrado antes de comprometer una cifra.' },
  { term: 'cabe señalar', gloss: 'it is worth pointing out', category: 'set_phrase', level: 'B2',
    example: 'Cabe señalar que la demora se originó en la entrega de información.' },
  { term: 'salvo que', gloss: 'unless (takes the subjunctive)', category: 'set_phrase', level: 'B2',
    example: 'Mantenemos el cronograma salvo que el cliente modifique el alcance.' },
  { term: 'a la brevedad', gloss: 'as soon as possible (formal)', category: 'set_phrase', level: 'B2',
    example: 'Agradeceré su respuesta a la brevedad para no afectar el plazo.' },
  { term: 'por nuestra parte', gloss: 'for our part', category: 'set_phrase', level: 'B2',
    example: 'Por nuestra parte, el expediente quedó entregado dentro del plazo.' },
  /* =================================================================== *
   * Second pass: the words a B2 speaker needs to be *precise* rather
   * than merely understood.
   *
   * The first pass covered what you cannot say without. This one covers
   * what separates «hubo un problema» from «se detectó una interferencia
   * que obligó a reprogramar el vaciado» — the difference an examiner
   * hears immediately and a client hears without knowing why.
   * =================================================================== */

  /* ---------------- connectors: precision about relationships ---------------- */
  { term: 'a fin de que', gloss: 'so that (+ subjunctive)', category: 'connector', level: 'B2',
    example: 'Enviamos el expediente hoy a fin de que el cliente lo revise antes del comité.' },
  { term: 'siempre que', gloss: 'as long as, provided (+ subjunctive)', category: 'connector', level: 'B2',
    example: 'Podemos adelantar la partida siempre que se libere el frente.' },
  { term: 'por consiguiente', gloss: 'consequently (formal register)', category: 'connector', level: 'B2',
    example: 'No se levantaron las observaciones; por consiguiente, la valorización queda en suspenso.' },
  { term: 'en todo caso', gloss: 'in any case, at any rate', category: 'connector', level: 'B1',
    example: 'En todo caso, dejaremos constancia en el acta antes de retirarnos.' },
  { term: 'pese a que', gloss: 'despite the fact that', category: 'connector', level: 'B2',
    example: 'Pese a que el plazo se mantiene, el riesgo de penalidad sigue vigente.' },

  /* ---------------- the words that make a claim precise ---------------- */
  { term: 'el hito', gloss: 'milestone', category: 'work_noun', level: 'B2',
    example: 'El siguiente hito contractual es la entrega del casco estructural.' },
  { term: 'la holgura', gloss: 'float, slack (in a schedule)', category: 'work_noun', level: 'B2',
    example: 'La ruta crítica ya no tiene holgura; cualquier retraso se traslada a la entrega.' },
  { term: 'la ruta crítica', gloss: 'critical path', category: 'work_noun', level: 'B2',
    example: 'El montaje de estructura entró a la ruta crítica tras el retraso del acero.' },
  { term: 'el entregable', gloss: 'deliverable', category: 'work_noun', level: 'B2',
    example: 'El entregable de esta etapa es el expediente técnico completo.' },
  { term: 'el replanteo', gloss: 'setting out, staking out', category: 'work_noun', level: 'B2',
    example: 'El replanteo topográfico se ejecutó antes del vaciado de cimientos.' },
  { term: 'la subsanación', gloss: 'remedying, correction of defects', category: 'work_noun', level: 'C1',
    example: 'La subsanación de observaciones tiene un plazo de diez días hábiles.' },
  { term: 'el precedente', gloss: 'precedent', category: 'work_noun', level: 'B2',
    example: 'Aceptar ese cambio sin adenda sentaría un precedente incómodo.' },
  { term: 'la salvedad', gloss: 'caveat, qualification', category: 'work_noun', level: 'C1',
    example: 'Firmamos el acta con la salvedad de que el metrado será revisado.' },
  { term: 'el respaldo', gloss: 'backing, supporting documentation', category: 'work_noun', level: 'B2',
    example: 'El adicional requiere respaldo técnico y sustento de costos.' },
  { term: 'el sustento', gloss: 'justification, supporting evidence', category: 'work_noun', level: 'B2',
    example: 'Presentamos el sustento del mayor metrado con planos as-built.' },
  { term: 'el vencimiento', gloss: 'expiry, due date', category: 'work_noun', level: 'B1',
    example: 'El vencimiento de la carta fianza es el treinta de noviembre.' },

  /* ---------------- verbs that carry a precise claim ---------------- */
  { term: 'deslindar responsabilidades', gloss: 'to establish who is responsible', category: 'collocation', level: 'C1',
    example: 'Antes de asumir el costo conviene deslindar responsabilidades por escrito.' },
  { term: 'dejar constancia', gloss: 'to place on record', category: 'collocation', level: 'B2',
    example: 'Dejamos constancia en el acta de que el frente no estaba liberado.' },
  { term: 'levantar observaciones', gloss: 'to close out defects', category: 'collocation', level: 'B2',
    example: 'La cuadrilla levantó las observaciones en menos de una semana.' },
  { term: 'liberar el frente', gloss: 'to release the work face', category: 'collocation', level: 'B2',
    example: 'No podemos iniciar el montaje hasta que liberen el frente.' },
  { term: 'incurrir en', gloss: 'to incur (a cost, a delay, a breach)', category: 'verb_pattern', level: 'C1',
    example: 'El proyecto incurrió en un retraso de veintidós días calendario.' },
  { term: 'ceñirse a', gloss: 'to stick to, to adhere to', category: 'verb_pattern', level: 'C1',
    example: 'Nos ceñimos a lo establecido en el expediente técnico.' },
  { term: 'constatar', gloss: 'to verify on site, to ascertain', category: 'verb_pattern', level: 'C1',
    example: 'Constatamos en campo que el acero colocado corresponde al plano.' },
  { term: 'obedecer a', gloss: 'to be due to (a cause)', category: 'verb_pattern', level: 'C1',
    example: 'El retraso obedece a la demora en la aprobación del adicional.' },
  { term: 'trasladar', gloss: 'to pass on (a cost, a delay)', category: 'verb_pattern', level: 'B2',
    example: 'Cualquier retraso adicional se traslada directamente a la fecha de entrega.' },

  /* ---------------- false friends that cost money ---------------- */
  { term: 'asistir', gloss: 'to attend — NOT "to assist"', category: 'false_friend', level: 'B1',
    example: 'Asistí a la reunión de coordinación. («To assist» is «ayudar».)' },
  { term: 'pretender', gloss: 'to intend, to aim to — NOT "to pretend"', category: 'false_friend', level: 'B2',
    example: 'Pretendemos cerrar la partida esta semana. («To pretend» is «fingir».)' },
  { term: 'la conducta', gloss: 'behaviour — NOT "conduct (a pipe)"', category: 'false_friend', level: 'B2',
    example: 'La conducta del subcontratista en obra fue observada. (A duct is «el ducto».)' },
  { term: 'soportar', gloss: 'to bear, to withstand — NOT "to support (an idea)"', category: 'false_friend', level: 'B2',
    example: 'La viga soporta la carga prevista. (To back a proposal is «respaldar».)' },

  /* ---------------- set phrases for meetings ---------------- */
  { term: 'quisiera plantear un punto', gloss: 'I would like to raise a point', category: 'set_phrase', level: 'B2',
    example: 'Antes de cerrar el acta, quisiera plantear un punto sobre el metrado.' },
  { term: 'si me permite', gloss: 'if I may', category: 'set_phrase', level: 'B2',
    example: 'Si me permite, hay un tema de interferencias que conviene revisar.' },
  { term: 'en aras de', gloss: 'for the sake of', category: 'set_phrase', level: 'C1',
    example: 'En aras de cumplir el plazo, proponemos trabajar los sábados.' },
  { term: 'a efectos de', gloss: 'for the purposes of', category: 'set_phrase', level: 'C1',
    example: 'A efectos de la valorización, el avance se corta el día veinticinco.' },
  { term: 'valga la aclaración', gloss: 'let me be clear about this', category: 'set_phrase', level: 'C1',
    example: 'Valga la aclaración: el adicional no cubre el cambio de especificación.' },
  { term: 'corríjame si me equivoco', gloss: 'correct me if I am wrong', category: 'set_phrase', level: 'B2',
    example: 'Corríjame si me equivoco, pero el plazo original vencía el quince.' },
  { term: 'coincido con usted en que', gloss: 'I agree with you that', category: 'set_phrase', level: 'B2',
    example: 'Coincido con usted en que el frente debió liberarse antes.' },
  { term: 'no comparto ese criterio', gloss: 'I do not share that view (polite disagreement)', category: 'set_phrase', level: 'C1',
    example: 'Con todo respeto, no comparto ese criterio sobre la responsabilidad del retraso.' },
  { term: 'entiendo su posición, sin embargo', gloss: 'I understand your position, however', category: 'set_phrase', level: 'B2',
    example: 'Entiendo su posición, sin embargo el contrato es claro en ese punto.' },
  { term: 'lo dejamos para la siguiente sesión', gloss: 'let us park it for the next meeting', category: 'set_phrase', level: 'B2',
    example: 'Si no hay consenso hoy, lo dejamos para la siguiente sesión.' },
];